### ISSUE TITLE
[Bug] Failed to build because of vite-plugin-html

### ISSUE THREAD

**Issue by Onion2222** [Kaetram/Kaetram-Open#168]
## About

Hello, I'm currently trying to build Kaetram on a raspberry 4B (arm64). But it failed each time I launch `yarn build` with this output:
```
instrum@xxxxx:~/games/Kaetram-Open-develop $ yarn build
➤ YN0000: [@kaetram/client]: Process started
➤ YN0000: [@kaetram/hub]: Process started
➤ YN0000: [@kaetram/server]: Process started
➤ YN0000: [@kaetram/hub]: Process exited (exit code 0), completed in 38s 532ms
➤ YN0000: [@kaetram/client]: failed to load config from /home/instrum/games/Kaetram-Open-develop/packages/client/vite.config.ts
➤ YN0000: [@kaetram/client]: error during build:
➤ YN0000: [@kaetram/client]: /home/instrum/games/Kaetram-Open-develop/node_modules/vite-plugin-html/dist/index.cjs:125
➤ YN0000: [@kaetram/client]:       const proxy = viteConfig.server?.proxy ?? {};
➤ YN0000: [@kaetram/client]:                                       ^
➤ YN0000: [@kaetram/client]: 
➤ YN0000: [@kaetram/client]: SyntaxError: Unexpected token '.'
➤ YN0000: [@kaetram/client]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
➤ YN0000: [@kaetram/client]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
➤ YN0000: [@kaetram/client]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
➤ YN0000: [@kaetram/client]:     at Module.load (internal/modules/cjs/loader.js:863:32)
➤ YN0000: [@kaetram/client]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
➤ YN0000: [@kaetram/client]:     at Module.require (internal/modules/cjs/loader.js:887:19)
➤ YN0000: [@kaetram/client]:     at require (internal/modules/cjs/helpers.js:74:18)
➤ YN0000: [@kaetram/client]:     at Object.<anonymous> (/home/instrum/games/Kaetram-Open-develop/packages/client/vite.config.ts:50:31)
➤ YN0000: [@kaetram/client]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
➤ YN0000: [@kaetram/client]:     at Object.require.extensions.<computed> [as .ts] (/home/instrum/games/Kaetram-Open-develop/node_modules/vite/dist/node/chunks/dep-611778e0.js:61506:20)
➤ YN0000: [@kaetram/client]: Process exited (exit code 1), completed in 49s 776ms
➤ YN0000: [@kaetram/server]: Process exited (exit code 0), completed in 55s 276ms
➤ YN0000: Done in 55s 487ms
```

### How to Reproduce

1. Download the archive of the git repo (i can't git clone because of a strange behavior of my bandwidth using git)
2. Unzip and go to the directory created
3. Execute `yarn`
4. Execute `yarn build`

### Expected behavior

Kaetram being built with exit code 0

### Environment

- Device: Raspberry PI 4B
- OS: Debian GNU/Linux 11 (bullseye) aarch64
- Browser: NA
- Kaetram Version 1.3.1 (as written in package.json)

### Additional context

This is the full procedure:
```
instrum@xxxxx:~/games/Kaetram-Open-develop $ yarn rebuild
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 828ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 996ms
➤ YN0000: ┌ Link step
➤ YN0007: │ kaetram@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.14.27 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.14.34 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.21.1 must be built because it never has been before or the last one failed
➤ YN0007: │ pngquant-bin@npm:6.0.0 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 4s 907ms
➤ YN0000: Done in 8s 491ms
instrum@xxxxx:~/games/Kaetram-Open-develop $ yarn build
➤ YN0000: [@kaetram/client]: Process started
➤ YN0000: [@kaetram/hub]: Process started
➤ YN0000: [@kaetram/server]: Process started
➤ YN0000: [@kaetram/hub]: Process exited (exit code 0), completed in 38s 532ms
➤ YN0000: [@kaetram/client]: failed to load config from /home/instrum/games/Kaetram-Open-develop/packages/client/vite.config.ts
➤ YN0000: [@kaetram/client]: error during build:
➤ YN0000: [@kaetram/client]: /home/instrum/games/Kaetram-Open-develop/node_modules/vite-plugin-html/dist/index.cjs:125
➤ YN0000: [@kaetram/client]:       const proxy = viteConfig.server?.proxy ?? {};
➤ YN0000: [@kaetram/client]:                                       ^
➤ YN0000: [@kaetram/client]: 
➤ YN0000: [@kaetram/client]: SyntaxError: Unexpected token '.'
➤ YN0000: [@kaetram/client]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
➤ YN0000: [@kaetram/client]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
➤ YN0000: [@kaetram/client]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
➤ YN0000: [@kaetram/client]:     at Module.load (internal/modules/cjs/loader.js:863:32)
➤ YN0000: [@kaetram/client]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
➤ YN0000: [@kaetram/client]:     at Module.require (internal/modules/cjs/loader.js:887:19)
➤ YN0000: [@kaetram/client]:     at require (internal/modules/cjs/helpers.js:74:18)
➤ YN0000: [@kaetram/client]:     at Object.<anonymous> (/home/instrum/games/Kaetram-Open-develop/packages/client/vite.config.ts:50:31)
➤ YN0000: [@kaetram/client]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
➤ YN0000: [@kaetram/client]:     at Object.require.extensions.<computed> [as .ts] (/home/instrum/games/Kaetram-Open-develop/node_modules/vite/dist/node/chunks/dep-611778e0.js:61506:20)
➤ YN0000: [@kaetram/client]: Process exited (exit code 1), completed in 49s 776ms
➤ YN0000: [@kaetram/server]: Process exited (exit code 0), completed in 55s 276ms
➤ YN0000: Done in 55s 487ms
```

I already reinstalled yarn, re-cloned Kaetram, deleted cache and node_modules and reinstalled packages with yarn... But I don't really know yarn and I don't understand the issue... Thanks a lot for your help.

yarn & node version:
```
instrum@xxxxx:~/games/Kaetram-Open-develop $ node --version
v12.22.5
instrum@xxxxx:~/games/Kaetram-Open-develop $ yarn --version
3.2.0
```

**Comment by lemueldls** [comment]
Support for Node.js 12.x is unsupported, try again with a Node.js version 14.x or higher.

**Comment by Onion2222** [comment]
Copy that,
Do you think I can use `n` ?
Thank you very much for your help

**Comment by lemueldls** [comment]
Sure, whatever version manager works.

**Comment by Onion2222** [comment]
Note:
Your README say `You need to use a Node.js version greater than or equal to v12.20.0`. I suppose it's outdated.

Thank you very much for your great fork !

**Comment by lemueldls** [comment]
Ah, right. Thanks, I've been meaning to update that!
